# Generated by Django 6.0.5 on 2026-05-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental', models.FloatField()),
                ('social', models.FloatField()),
                ('governance', models.FloatField()),
                ('composite', models.FloatField()),
                ('source', models.CharField(default='internal', max_length=120)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to='companies.company')),
            ],
        ),
    ]
