# Generated by Django 6.0.5 on 2026-05-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('ticker', models.CharField(max_length=30, unique=True)),
                ('esg_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(default='moderate', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
